apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-streaming-recoverable-kafka-word-count
  namespace: default
spec:
  type: Java
  mode: cluster
  image: "sample-spark-job-image"
  imagePullPolicy: IfNotPresent
  mainClass: spark.examples.streaming.RecoverableKafkaWordCount
  mainApplicationFile: "local:///opt/spark/custom-spark-job/sample-spark-job.jar"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-pv-claim
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
      - name: spark-data
        mountPath: "/data"
